name: MLOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start MLflow Tracking Server
        run: |
          mkdir -p mlruns
          nohup mlflow server --backend-store-uri sqlite:///mlflow.db --host 127.0.0.1 --port 5000 > mlflow.log 2>&1 &
          sleep 10  # Give MLflow time to start

      - name: Ensure models directory exists
        run: mkdir -p models

      - name: Train the Model
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000  # Set MLflow tracking URI
        run: python scripts/train.py

      - name: Debug model directory
        run: ls -R models || echo "models directory not found"

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl
          if-no-files-found: error  # Fails the workflow if model.pkl is missing

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Build Docker image
        run: docker build -t mlops-app -f ./api/Dockerfile .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag mlops-app ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
