name: MLOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure models directory exists
        run: mkdir -p models mlruns

      - name: Train the Model
        env:
          MLFLOW_TRACKING_URI: https://82a0-103-246-243-242.ngrok-free.app   # Set MLflow tracking URI
        run: python scripts/train.py

      - name: Debug model directory
        run: ls -R models || echo "models directory not found"

      - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl
          if-no-files-found: error  # Fails the workflow if model.pkl is missing

      - name: Upload MLflow artifacts
        if: always()  # Ensures it runs even if previous steps fail
        run: |
          if [ -d "mlruns" ] && [ "$(ls -A mlruns)" ]; then
            echo "Uploading MLflow artifacts..."
          else
            echo "ERROR: mlruns/ directory not found!"
            exit 1
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/

      - name: Build Docker image
        run: docker build -t mlops-app -f ./api/Dockerfile .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag mlops-app ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-app:latest
